# Generated by Django 2.2.6 on 2019-11-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='NULL', upload_to='images/')),
                ('time', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('user', models.CharField(max_length=500)),
                ('screenId', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('screenId', models.BigIntegerField()),
                ('user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('time', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('screenId', models.BigIntegerField()),
            ],
        ),
    ]
